AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 100

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - '**/spec/*_spec.rb'
