name: CI
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
          bundler-cache: true
      - name: Rubocop Lint
        run: bundle exec rubocop
      - name: RSpec tests
        run: bundle exec rspec --format d
